### ISSUE TITLE
How do we get the tool?

### ISSUE THREAD

**Issue by sexfrance** [iLxlo/Admaven#1]
How do we get the tool?

**Comment by iLxlo** [comment]
Hello please join our discord server https://discord.gg/Z2eZxXbUaS

**Comment by sexfrance** [comment]
Hey, the link is invalid

**Comment by sexfrance** [comment]
never mind,

**Comment by iLxlo** [comment]
Its not, maybe you are ratelimited

**Comment by sexfrance** [comment]
Nah I just have bad internet and it bugs it says invalid on web but valid on discord app
